Project/Redemption/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^home/', include('home.urls', namespace="home")),	
    url(r'^wiki/', include('wiki.urls', namespace="wiki")),
    url(r'^login/', include('login.urls', namespace="login")),	
]

Project/home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [ 
	
	url(r'^',views.home, name='home'),  
]

Project/wiki/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [ 
	
	url(r'^$',views.wiki, name='wiki'), 
	url(r'^Categories/',views.categories, name='categories'),
	url(r'^Category/?(?P<test>\w+/?)/',views.category, name='category'),
	url(r'^Article/?(?P<test>\w+?/?)/',views.article, name='article'),
	url(r'^Edit/(?P<eai>\w+)/',views.edit_article_content, name='edit_article_content'),
	
	url(r'^History/(?P<hai>\w+)/',views.article_history, name='article_history'),
	url(r'^Content Reverted/(?P<ri>\w+)/(?P<related>\w+)',views.revert_content, name='revert_content'),
	


	url(r'^Add Category/',views.add_category, name='add_category'),
	url(r'^Add Article/(?P<categoryID>\w+)/',views.add_article, name='add_article'),
	#url(r'^',views.category, name='category'),
	#url(r'^',views.article, name='article'),
	

	#url(r'^x/Basil/', views.view_article, name='view_article'),
	#url(r'^Category/(?P<article_title>)', views.view_article, name='view_article'),
	#url(r'^Category/([A-Za-z]+)/(?P<article_title>)', views.view_article, name='view_article'),
	
	
	


	
]

Project/wiki/models.py
from django.db import models
from django.utils import timezone

class Category(models.Model):
	category_title = models.CharField(max_length='140',default="New Category")

	def __str__(self):
		return self.category_title
	
class Article(models.Model):
	article_title = models.TextField(max_length='140',default="New Article")
	article_content = models.TextField(max_length='140',default="New Article",null=True)
	category = models.ForeignKey(Category)

	def __str__(self):
		return self.article_title

class Article_Content_History (models.Model):
	article_author_id = models.TextField(default='Empty',null=True)
	article_author = models.TextField(default='Empty',null=True)
	article_content_history=models.TextField(default='Empty',null=True)
	article_related = models.TextField(default='Empty',null=True)
	article_content_history_timestamp = models.DateTimeField('Timestamp',default=timezone.now())
	
	def __str__(self):
		return self.article_content_history_timestamp

Project/wiki/forms.py
from django import forms
from .models import Article

class PostForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title', 'int',)

Project/wiki/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.template import RequestContext, loader
from django.shortcuts import redirect
from wiki.models import Category
from wiki.models import Article
from wiki.models import Article_Content_History
from django.contrib.auth.models import User
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.core.files.storage import FileSystemStorage
import Image
import imghdr
import os
import os.path






def wiki(request):
	if request.user.is_active:
		try:
				uauth = request.session['auth']
				if (uauth == '0') or (uauth == '1') or (uauth == '2'):
					userid = request.session['user_id']
					fullname = request.session['fullname']
					myuser = User.objects.get(pk=userid)

					userimage = 'wiki/images/' + myuser.username + '.jpeg'
			   		testimage = 'wiki/static/' + userimage
			   		userauth = str(myuser.profile.user_auth)


			   		#VALIDATES FILE EXISTS
			   		if os.path.isfile(testimage) == False:
			   			userimage = 'wiki/images/guest.gif'

					context = {'userauth':userauth,'userauth':userauth,'userid': userid , 'fullname': fullname, 'userimage': userimage }
					return render(request, 'wiki/wiki.html', context)
				else:
					return render(request, 'wiki/wiki.html')

		except KeyError:
			return render(request, 'wiki/wiki.html')
	else:
		return render(request, 'wiki/wiki.html')

def categories(request):

	categories = Category.objects.all()
	context = {'categories': categories }
	if request.user.is_active:
		uauth = request.session['auth']
		if (uauth == '0') or (uauth == '1') or (uauth == '2'):
			try:
				userid = request.session['user_id']
				fullname = request.session['fullname']
				myuser = User.objects.get(pk=userid)
				userauth = str(myuser.profile.user_auth)

				userimage = 'wiki/images/' + myuser.username + '.jpeg'
				
		   		
		   		testuserimage = 'wiki/static/' + userimage
		   		

		   		#VALIDATES FILE EXISTS
		   		if os.path.isfile(testuserimage) == False:
		   			userimage = 'wiki/images/guest.gif'
		   		
				
				context = {'userauth':userauth,'categories': categories, 'userid': userid , 'fullname': fullname,  'userimage': userimage  }
				return render(request, 'wiki/categories.html',context)
			except KeyError:
				return render(request, 'wiki/categories.html',context)
		else:
			return render(request, 'wiki/categories.html', context)
	else:
		return render(request, 'wiki/categories.html', context)

def category(request, test):
	articles = Article.objects.filter(category_id=test)
	thiscat = Category.objects.filter(id=test)[0]
	context = {'articles': articles,'thiscat':thiscat,}
	if request.user.is_active:
		uauth = request.session['auth']
		if (uauth == '0') or (uauth == '1') or (uauth == '2'):
			try:
				userid = request.session['user_id']
				fullname = request.session['fullname']
				myuser = User.objects.get(pk=userid)
				userauth = str(myuser.profile.user_auth)


				userimage = 'wiki/images/' + myuser.username + '.jpeg'
				
		   		
		   		testuserimage = 'wiki/static/' + userimage
		   		

		   		#VALIDATES FILE EXISTS
		   		if os.path.isfile(testuserimage) == False:
		   			userimage = 'wiki/images/guest.gif'
		   		

   			

				context = {'userauth':userauth,'articles': articles,'thiscat':thiscat, 'userid': userid , 'fullname': fullname,  'userimage': userimage  }
				return render(request, 'wiki/category.html', context)

			except KeyError:
				return render(request, 'wiki/category.html', context)
		else:
			return render(request, 'wiki/category.html', context)
	else:
		return render(request, 'wiki/category.html', context)


	

def article(request, test):
	
	thisArticle = Article.objects.get(id=test)
	artimage = 'wiki/images/articles/' + str(thisArticle.id) + '.jpeg'
	testartimage = 'wiki/static/' + artimage
	#VALIDATES FILE EXISTS
   	if os.path.isfile(testartimage) == False:
   		artimage = 'wiki/images/articles/none.jpeg'
	context = {'artimage':artimage,'thisArticle': thisArticle}

	if request.user.is_active:
		uauth = request.session['auth']
		if (uauth == '0') or (uauth == '1') or (uauth == '2'):
			try:
				userid = request.session['user_id']
				fullname = request.session['fullname']
				myuser = User.objects.get(pk=userid)
				userauth = str(myuser.profile.user_auth)

				userimage = 'wiki/images/' + myuser.username + '.jpeg'
				artimage = 'wiki/images/articles/' + str(thisArticle.id) + '.jpeg'
		   		
		   		testuserimage = 'wiki/static/' + userimage
		   		testartimage = 'wiki/static/' + artimage

		   		#VALIDATES FILE EXISTS
		   		if os.path.isfile(testuserimage) == False:
		   			userimage = 'wiki/images/guest.gif'
		   		

   				#VALIDATES FILE EXISTS
   				if os.path.isfile(testartimage) == False:
   					artimage = 'wiki/images/articles/none.jpeg'


				context = {'userauth':userauth,'thisArticle': thisArticle,'userid': userid , 'fullname': fullname  ,'userimage': userimage, 'artimage': artimage   }
				return render(request, 'wiki/article.html',context)
			except KeyError:
				return render(request, 'wiki/article.html',context)
		else:
			return render(request, 'wiki/article.html', context)
	else:
		return render(request, 'wiki/article.html', context)

def edit_article_content(request ,eai):
	thisArticle = Article.objects.get(id=eai)
	context = {'thisArticle': thisArticle}
	if request.user.is_active:
		uauth = request.session['auth']
		if (uauth == '1') or (uauth == '2'):
			try:
				userid = request.session['user_id']
				fullname = request.session['fullname']
				myuser = User.objects.get(pk=userid)
				userauth = str(myuser.profile.user_auth)

				#EDITING
				selected_choice = request.POST.get('intro')
				
				thisArticle.article_content =selected_choice
				thisArticle.save()

				savehistory = Article_Content_History.objects.create(article_author_id=userid, article_author=fullname,article_related=eai, article_content_history=selected_choice)
				savehistory.save()

				thisArticle=Article.objects.get(id=eai)
				#END OF EDITING

				userimage = 'wiki/images/' + myuser.username + '.jpeg'
				artimage = 'wiki/images/articles/' + str(thisArticle.id) + '.jpeg'
		   		
		   		testuserimage = 'wiki/static/' + userimage
		   		testartimage = 'wiki/static/' + artimage

		   		#VALIDATES FILE EXISTS
		   		if os.path.isfile(testuserimage) == False:
		   			userimage = 'wiki/images/guest.gif'
		   		

   				#VALIDATES FILE EXISTS
   				if os.path.isfile(testartimage) == False:
   					artimage = 'wiki/images/articles/none.jpeg'

				context = {'artimage': artimage,'userauth':userauth,'thisArticle': thisArticle,'userid': userid , 'fullname': fullname, 'userimage': userimage,   }
				return render(request, 'wiki/article.html',context)
			except KeyError:
				return render(request, 'wiki/article.html',context)
		else:
			return render(request, 'wiki/article.html', context)
	else:
		return render(request, 'wiki/article.html', context)

#HISTORY
def article_history(request ,hai):
	print("content hist")
	thisArticle=Article.objects.get(id=hai)
	thisHistory = list(Article_Content_History.objects.filter(article_related=hai).order_by('-article_content_history_timestamp')[:5])

	uauth = request.session['auth']
	if (uauth == '0') or (uauth == '1') or (uauth == '2'):
		try:
			userid = request.session['user_id']
			fullname = request.session['fullname']
			myuser = User.objects.get(pk=userid)
			userauth = str(myuser.profile.user_auth)

			userimage = 'wiki/images/' + myuser.username + '.jpeg'
	   		testimage = 'wiki/static/' + userimage
	   		#VALIDATES FILE EXISTS
	   		userimage = 'wiki/images/' + myuser.username + '.jpeg'
			artimage = 'wiki/images/articles/' + str(thisArticle.id) + '.jpeg'
		   		
		   	testuserimage = 'wiki/static/' + userimage
		   	testartimage = 'wiki/static/' + artimage

		   	#VALIDATES FILE EXISTS
		   	if os.path.isfile(testuserimage) == False:
		   		userimage = 'wiki/images/guest.gif'
		   		

   			#VALIDATES FILE EXISTS
   			if os.path.isfile(testartimage) == False:
   				artimage = 'wiki/images/articles/none.jpeg'


			context = {
			'artimage': artimage,
			'userauth':userauth,
			'thisArticle': thisArticle,
			'thisHistory': thisHistory,
			'userid': userid ,
			'fullname': fullname,
		 	'userimage': userimage,
			}
			return render(request, 'wiki/article.html',context)
		except KeyError:
			context = {'thisArticle': thisArticle,
			'thisHistory': thisHistory

			}
			return render(request, 'wiki/article.html',context)
	else:
		context = {'thisArticle': thisArticle,
			'thisHistory': thisHistory

			}
		return render(request, 'wiki/categories.html', context)



##HISTORY REVERT
def revert_content(request ,ri , related):
	thisArticle=Article.objects.get(id=ri)
	history=Article_Content_History.objects.get(id=related)
	 
	thisArticle.article_content = history.article_content_history
	thisArticle.save()

	uauth = request.session['auth']
	if (uauth == '1') or (uauth == '2'):

		try:
			userid = request.session['user_id']
			fullname = request.session['fullname']
			myuser = User.objects.get(pk=userid)
			userauth = str(myuser.profile.user_auth)

			userimage = 'wiki/images/' + myuser.username + '.jpeg'
			artimage = 'wiki/images/articles/' + str(thisArticle.id) + '.jpeg'
		   		
		   	testuserimage = 'wiki/static/' + userimage
		   	testartimage = 'wiki/static/' + artimage

		   	#VALIDATES FILE EXISTS
		   	if os.path.isfile(testuserimage) == False:
		   		userimage = 'wiki/images/guest.gif'
		   		

   			#VALIDATES FILE EXISTS
   			if os.path.isfile(testartimage) == False:
   				artimage = 'wiki/images/articles/none.jpeg'
		
			
			context = {
			'artimage': artimage,
			'userauth':userauth,
			'thisArticle': thisArticle,
			'userid': userid ,
			'fullname': fullname,
			'userimage': userimage,   }

			return render(request, 'wiki/article.html',context)
		except KeyError:
			context = {'thisArticle': thisArticle,

Project/wiki/templates/wiki/article.html
{% extends 'newbase.html' %}
{% load custom_markdown %}
	{% block content %}

  

	<h1>{{thisArticle.article_title}}</h1>
  <div id="ArticleContent">
	{% load static from staticfiles %}
  	{% static artimage as artpic %}
  
  	<div id="ArticleImage"><img src="{{artpic}}" alt="{{artpic}}" /></div>
  	{{thisArticle.article_content|custom_markdown}}
  
  </div>

  {% if fullname %}
  {% if userauth == '1' or userauth == '2' %}
    <button id="EditContents" type="button" class="btn btn-primary" >Edit</button>
    <div id = "EditContentDiv" style="display:none">
    <ul>
    <h2>Article Style Tools</h2>
    <hr/>
    <li>*yourtext* : Italics</li>
    <li>**yourtext** : Bold</li>
    <li>***yourtext*** : Bold+Italics</li>
    <li>* yourtext : list</li>
    <li>[linkname](linkurl) : link</li>
    </ul>

    <form id="Edit" action="{% url 'wiki:edit_article_content' thisArticle.id %} " method="post">
    {% csrf_token %}
    <textarea type="text" rows="20" cols="100" name="intro" id="ContentChangeField">{{thisArticle.article_content}}</textarea>
    <input type="submit" value="Save Changes" class="btn btn-success" id="Savings"/>
    </form>

    </div> 

      {% if userauth == '2' %}          
    <form action="{% url 'wiki:article_history' thisArticle.id %} " method="post">  
    {% csrf_token %}
    <input id="ViewIntroductionHistory_Button" type="submit" value="History" class="btn btn-primary" /> 
    </form>

  	
    
  {% endif %} {% else %}

  <div id="ArticleContent">
    <h6>Log in as a registered user to edit</h6>
  <div>

  {% endif %}



  {% if thisHistory %}
  <div id = "Content_History_Div" >
  {% for hist in thisHistory %} 	

  <form action="{% url 'wiki:revert_content' thisArticle.id hist.id %} " method="post">  
  {% csrf_token %}                                    
  <p>
  Last Edited: 
  {{ hist.article_content_history_timestamp }} 
  
  by User:
  {{ hist.article_author }} 
	<input  name="{{hist.id}}" type="submit" value="Revert" class="btn btn-primary" />
	</p>
	</form>                                          		
  
  {% endfor %}	{% endif %} 
  {% endif %} 	

	</div> 


 <script type="text/javascript">
   EditContents = document.getElementById('EditContents');
   ViewIntroductionHistory_Button = document.getElementById('ViewIntroductionHistory_Button');
   
   

   EditContentDiv = document.getElementById('EditContentDiv');
   Content_History_Div = document.getElementById('Content_History_Div');


   ContentChangeField = document.getElementById('ContentChangeField');
 
                  
   EditContents.onclick = function() 
   { 
   var isHidden = EditContentDiv.style.display == 'none';
   EditContentDiv.style.display = isHidden ? 'block' : 'none'   
   }
   ViewIntroductionHistory_Button.onclick = function() 
   { 
   var isHidden = Content_History_Div.style.display == 'none';
   Content_History_Div.style.display = isHidden ? 'block' : 'none'   
   }
   </script>




{% endblock %}
      

Project/wiki/templates/wiki/categories.html
{% extends 'newbase.html' %}
	{% block content %}

 	{% load static from staticfiles %}


  	{% if categories %}
    <div class="row-marketing">
      <div class="row">
  	   <ul class="CategoryList">

        {% if userauth == '1' or  userauth == '2'%}
      	<li>
        		{% if fullname %}
        	  	<form action="{% url 'wiki:add_category' %} " method="post">
                  <legend><h1>Add A New Category</h1></legend>
        	  	{% csrf_token %}
              <div class="form-group">
                  <label for="InputCategory">Category Name</label>
                 <div class="input-group">
        	  	    <input class="form-control" type="textarea" name="Title" placeholder="New Category Name" rows="100" cols="50" Required/>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                  </div>
                </div>
              <div class="form-group">
        	  	<input id="Add_Category" type="submit" Value="Add New Category"class="btn btn-primary"/>
              </div>
        	  	</form>
            {% endif %}
       	{% else %}
      	  	  Log in as a registered user to create &#9786;
      	{% endif %}
      	</li>
        <hr/>
          <h1>Categories Available</h1>
        <hr/>

      	{% for category in categories %}  
      	<div class="panel panel-primary"><a href="{% url 'wiki:category' category.id %}"><li> {{ category.category_title }}</li></a></div>
      	
      	{% endfor %} 
  </ul>
              </div>
        </div>
      	{% else %} 
      	<div class="panel panel-primary">No Categories</div>
  	{% endif %} 
    
	{% endblock %}




Project/wiki/templates/wiki/category.html
{% extends 'newbase.html' %}
	{% block content %}

  {% load static from staticfiles %}
  
  <div class="row">
    <ul class="CategoryList">
      {% if fullname %}
    <li>

    <form action="{% url 'wiki:add_article' thiscat.id %} " method="post" enctype='multipart/form-data'>
            <legend><h1>Add A New Article</h1></legend>
             {% csrf_token %}
             <div class="form-group">
                <label for="InputArticleTitle">Title</label>
                  <div class="input-group">
                    <input class="form-control" required type="textarea" name="Title" placeholder="Title"/>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                  </div>
              </div>
              <div class="form-group">
                <label for="InputArticleContent">Content</label>
                  <div class="input-group">
                    <textarea class="form-control" required type="textarea" name="Content" placeholder="Contents Here"></textarea>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                  </div>
              </div>
            <!--<div class="form-group">-->
		<label>Add My Image</label>
              <input type="file" name='articlepic' id="artpic" />
              {{error}}
            <!--</div>-->
            <div class="form-group">
    <input id="Add_Article" type="submit" value="Add New Article"  class="btn btn-primary"/>
    </div>
    </form>
  </li>
       

    {% else %}
    <li>Log in to create an Article &#9786;</li>
    {% endif %}
    <hr/>
        <h1>Articles Available</h1>
    <hr/>
  
    {% if articles %}

    {% for article in articles %}  
    <div class="panel panel-primary"><a href="{% url 'wiki:article' article.id %}"><li> {{ article.article_title }}</li></a></div>
    {% endfor %} 


    {% else %} 
    <div class="panel panel-primary"><li>No articles</li></div>
    {% endif %}   
  </ul>            
  </div>


{% endblock %}


Project/wiki/templates/wiki/wiki.html
{% extends 'newbase.html' %}
   {% block content %}

   {% load static from staticfiles %}

   <div class="WikiInfos">
            <h1>Welcome to the gardening world!</h1>

      <p class="lead">Welcome to wikis gardening world. On this site you get to collaborate and help build useful articles that is all about gardening. Share your gardening knowledge and make the world a better place. </p>



      <!-- START THE FEATURETTES -->

            <hr class="featurette-divider">

            <div class="row featurette">
             <div class="col-md-7">
               <h2 class="featurette-heading">Gardening is fun<span class="text-muted"></span></h2>
                <p class="lead">Find all your articles related to gardening here on Wiki's Gardening World. From how to grow different herbs, to articles around which pestisides to avoid. It can all be found here.</p>
         </div>
         <div class="col-md-5">
               <img class="featurette-image img-responsive center-block" src="/static/Shrubs.jpg" alt="Generic placeholder image" height="75%" width="75%">
             </div>
            </div>

            <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Share Your Knowledge<span class="text-muted"></span></h2>
          <p class="lead">Wiki allows you to put knowledge to use in collaborative ways. If you have advice on growing shrubs, trees, herbs or even even gardening tools write an article and share it with your friends.</p>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <img class="featurette-image img-responsive center-block" src="/static/Gardeners.JPG" alt="Generic placeholder image" height="20%" width="75%">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Collaboratively Generate Articles<span class="text-muted"></span></h2>
          <p class="lead">Once you write something the other wiki members are able to add to the pool of knowledge you've created. Thereby making this gardening wiki highly collaborative. See what your peers have to say today</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" src="/static/PeopleTexting.jpg" alt="Generic placeholder image" height="75%" width="75%" >
        </div>
      </div>

      <hr class="featurette-divider">

</div>
   {% endblock %}

